home:
  path: /
  controller: App\Controller\HomeController::template

#user:
 # path: /user
  #controller: App\Controller\UserController::index




#index:
#    path: /
#    controller: App\Controller\DefaultController::index
